### ISSUE TITLE
Open up mimosa-6to5?

### ISSUE THREAD

**Issue by dbashford** [YoloDev/mimosa-rename#1]
Would love to take a look. Wanted to try 6to5 myself. =)

**Comment by Alxandr** [comment]
Yeah, will open it up. Just had a computer break down, so have to go find it in backups and stuff :-/

**Comment by dbashford** [comment]
Ah, I had assumed given the URL in the package.json on NPM that it was in a private repo or something.  Just having it locally makes more sense.

Thanks!  Been itching to play with it.  I can definitely help out with the docs for that module if you'd like.

**Comment by Alxandr** [comment]
I would love it. Currently the docs are completely wrong (due to lazyness) ^^
Though, it would mostly be a matter of copy pasting from 6to5 docs (as all the options are mirrored).

**Comment by Alxandr** [comment]
https://github.com/YoloDev/mimosa-6to5
